### ISSUE TITLE
Smarter formatting of comment lines

### ISSUE THREAD

**Issue by dansalvato** [grahambates/m68k-lsp#5]
One thing I've noticed is that auto-formatting the document always results in comments being pushed to the "comments" column as specified, but typically, this is only desirable for an inline comment, i.e. one that follows an operand. Oftentimes, there is a line containing *only* a comment that is desirable to keep either left-aligned, or aligned with the mnemonic below it.

A few suggestions on possibly good ways of handling this:

1. Do not format lines that contain only a comment, or only whitespace and a comment
2. Add a separate `align` setting for lines that contain only comments
3. Add a `format` setting to always align comment-only lines with the mnemonic column, or even the column of choice (`mnemonic`/`operands`/`operator`/`value`). This would solve the problem of comments losing their alignment if an extra-long symbol name pushes the mnemonic column back a tab.
4. Have different behaviors or settings for comments prepended with either `;` or `*`, giving the user control over formatting based on comment character used (maybe not ideal if not all assemblers interpret both these characters as comments)

What do you think about these?

**Comment by grahambates** [comment]
Yeah I have thought about this. As you've seen, the current behaviour is to ignore lines where the comment is on the first character, otherwise align to comment position.

One additional option I'd considered was to snap to the nearest element position (i.e. label, mnemonic, operands or comment), based on the comment's current position. I might give this a try.

I agree all of this should be configurable. Options could be:

- ignore (don't align)
- nearest element
- label
- mnemonic
- operands
- comment

**Comment by dansalvato** [comment]
Thanks for your continued improvements! Let me know if there's any way I can be more accommodating with the way I share issues or suggestions in the future.

**Comment by grahambates** [comment]
No problem. Keep the feedback/suggestions coming!
